version: '3'

services:
  mobsos-data-processing:
    image: registry.tech4comp.dbis.rwth-aachen.de/rwthacis/mobsos-data-processing:master
    environment:
      MYSQL_HOST: db
      MYSQL_PORT: ${DATABASE_PORT:-3306}
      MYSQL_USER: ${DATABASE_USER:-root}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD:-root}
      LAS2PEER_PORT: 9013
      BOOTSTRAP: social-bot-manager:9011
    ports:
      - "9013:9013"
    depends_on:
      - social-bot-manager
  social-bot-manager:
    image: registry.tech4comp.dbis.rwth-aachen.de/rwthacis/social-bot-manager:ma-lakhoune
    environment:
      DATABASE_NAME: ${DATABASE_NAME:-SBF}
      DATABASE_HOST: db
      DATABASE_PORT: ${DATABASE_PORT:-3306}
      DATABASE_USER: ${DATABASE_USER:-root}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD:-root}
      WEBCONNECTOR_URL: ${WEBCONNECTOR_URL:-127.0.0.1:8080}
      MONGO_HOST: ${MONGO_HOST:-mongo:8080}
      MONGO_DB: ${MONGO_DB:-sbf}
      MONGO_USER: ${MONGO_USER:-admin}
      MONGO_PASSWORD: ${MONGO_PASSWORD:-password}
      MONGO_AUTH: ${MONGO_AUTH:-auth}
      LRS_URL: ${LRL_URL:-127.0.0.1:8080}
      LRS_AUTH_TOKEN: ${LRL_AUTH_TOKEN:-token} 
    ports:
      - "8080:8080"
      - "9011:9011"
    depends_on:
      - db
  
  yjs: 
    image: registry.tech4comp.dbis.rwth-aachen.de/rwthacis/y-websocket:master
    ports:
      - "1234:1234"
  
  rasa:
    image: ${RASA_IMAGE:-rasa/rasa:3.3.10-full}
    command: run --enable-api -m models --cors "*" --debug
  db:
    image: mysql:8
    platform: ${TARGETPLATFORM:-linux/amd64}
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD:-root}
      MYSQL_DATABASE: ${DATABASE_NAME:-SBF}
      MYSQL_INITDB_SQL: /docker-entrypoint-initdb.d/init.sql
    volumes:
      - ./assets/SBF.sql:/docker-entrypoint-initdb.d/init.sql

  frontend:
    build: . # or use image: <your image>
    # image: socialbotframework:latest 
    environment:
      YJS: ${YJS:-localhost:1234}
      PORT: ${PORT:-8082}
      OIDC_CLIENT_ID: ${OIDC_CLIENT_ID:-localtestclient}
      YJS_RESOURCE_PATH: ${YJS_RESOURCE_PATH:-/socket.io}
      RASA_NLU: ${RASA_NLU:-http://rasa:5005}
      SBF_MANAGER: ${SBF_MANAGER:-http://localhost:8080/SBFmanager}
      CONTACT_SERVICE_URL: ${CONTACT_SERVICE_URL:-http://localhost:8080/contactservice}
      YJS_PROTOCOL: ${YJS_PROTOCOL:-ws}
    depends_on:
      - yjs
      - rasa
      - social-bot-manager

    ports:
      - "8082:8082"
  mongo:
      image: mongo
      restart: always
      environment:
        MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER:-admin}
        MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD:-password}